# 兑换码配置文件

- code: "SRFG45A45W6E"
  description: "测试服专属奖励"
  type: "one_time_per_player"
  whitelist:
    - 3499269137
    - 3235482308
    - 1154725082
    - 1982975523
    - 214391698
    - 3177135505
    - 1354903463
    - 2283096140
    - 480730470
    - 2507239514
  rewards:
    - name: "2w"
      amount: 10
    - name: "七星玄元丹"
      amount: 5

- code: "ADSG5DF4Q"
  description: "版本更新补偿"
  type: "one_time_per_player"
  rewards:
    - name: "2w"
      amount: 6
    - name: "七星玄元丹"
      amount: 5
    - name: "花篮"
      amount: 10

- code: "2026xiuxianNewyeah"
  description: "2026新年快乐"
  type: "one_time_per_player"
  startTime: "2026-01-01 00:00:00"
  rewards:
    - name: "七星玄元丹"
      amount: 5
    - name: "2w"
      amount: 100