# 活动调度配置文件

# 默认通知的群聊ID，机器人必须在该群内
defaultGroup: 906061358

activities:
  - name: "寒江独钓"
    eventKey: "hanjiang_fishing_2025_10"
    startTime: "2025-12-10 11:33:00"
    endTime: "2026-01-10 23:59:59"
    context: "江雪初霁，鱼肥蟹美，正是垂钓的绝佳时机。活动期间可于江边垂钓，兑换限定宝物。发送【#寒江独钓】即可查看活动信息。"

  - name: "万象天机"
    eventKey: "wanxiang_tianji_2026_01"
    startTime: "2026-01-06 10:48:00"
    endTime: "2026-03-01 23:59:59"
    context: |
      天地为盘，星辰为子。
      一场模拟天地杀伐的幻境已然开启，修士可遣"星魂"入局，推演万象，夺取天机造化！