# 活动调度配置文件

# 默认通知的群聊ID，机器人必须在该群内
defaultGroup: 140651878

activities:
  - name: "寒江独钓"
    eventKey: "hanjiang_fishing_2025_10"
    startTime: "2025-10-07 09:57:00"
    endTime: "2025-10-07 17:56:00"
    context: "江雪初霁，鱼肥蟹美，正是垂钓的绝佳时机。活动期间可于江边垂钓，兑换限定宝物。"