# 在这里定义每月的累计签到奖励
# days: 累计签到天数
# name: 奖励阶段的名称
# rewards: 奖励物品列表，可以有多个
- days: 5
  name: "勤勉好礼"
  rewards:
    - name: "5k"
      class: "道具"
      amount: 1

- days: 15
  name: "持之以恒"
  rewards:
    - name: "2w"
      class: "道具"
      amount: 2

- days: 25
  name: "全勤仙尊"
  rewards:
    - name: "2w"
      class: "道具"
      amount: 5